name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release/**'

env:
  IMAGE_NAME: fcstask-frontend
  K8S_NAMESPACE_TEST: fcstask-frontend-test
  K8S_NAMESPACE_PROD: fcstask-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Prepare variables
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

  deploy-test-to-k8s:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Ensure namespace exists
        run: |
          kubectl create namespace ${{ env.K8S_NAMESPACE_TEST }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to test
        env:
          DB_HOST: postgres-dev-postgresql-primary.postgres-dev.svc.cluster.local
          DB_REPLICA_HOST: postgres-dev-postgresql-read.postgres-dev.svc.cluster.local
          DB_PORT: '5432'
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          helm upgrade --install fcsapp-frontend ./helm/fcsapp-frontend \
            --namespace ${{ env.K8S_NAMESPACE_TEST }} \
            --set image.repository=${{ secrets.DOCKER_REGISTRY_USER }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            --wait

  deploy-prod-to-k8s:
    needs:
      - build-and-push
      - deploy-test-to-k8s

    if: needs.build-and-push.outputs.is_release_branch == 'true'

    runs-on: self-hosted
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Ensure namespace exists
        run: |
          kubectl create namespace ${{ env.K8S_NAMESPACE_PROD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to prod
        env:
          IMAGE_REPOSITORY: ${{ secrets.DOCKER_REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ needs.build-and-push.outputs.short_sha }}
        run: |
          helm upgrade --install fcsapp-frontend ./helm/fcsapp-frontend \
            --namespace ${{ env.K8S_NAMESPACE_PROD }} \
            --set image.repository="$IMAGE_REPOSITORY" \
            --set image.tag="$IMAGE_TAG" \
            --wait \
            --timeout 5m
